before_install:
  - sudo apt-get install r-base
  - R -e 'r=getOption("repos"); r["CRAN"]="http://cran.cnr.berkeley.edu/";options(repos=r);install.packages("rjson")'

language: java

sudo: required

jdk:
  - openjdk7
  - oraclejdk7

script: mvn test
