before_install:
  - sudo apt-get install r-base
  - sudo R -e 'install.packages("rjson", repos="http://cran.cnr.berkeley.edu/")'

language: java

sudo: required

jdk:
  - openjdk7
  - oraclejdk7

script: mvn test
